In [52]:
import numpy as np
import torch
import torch.nn as nn

In [53]:
x = np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)
y = np.array([[0],[1],[1],[0]],dtype=np.float32)
x_tensor = torch.tensor(x)
y_tensor = torch.tensor(y)


In [54]:
model = nn.Sequential(
    nn.Linear(2,2),
    nn.Sigmoid(),
    nn.Linear(2,1),
    nn.Sigmoid()
)

In [55]:
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(),lr=0.01)

In [56]:
epochs = 1000
for epoch in range(epochs):
  model.train()
  optimizer.zero_grad()
  y_pred = model(x_tensor)
  loss = criterion(y_pred,y_tensor)
  loss.backward()
  optimizer.step()

  if epoch %100 ==0:
    print(f'Epoch: {epoch} Loss: {loss.item()}')
    for name, param in model.named_parameters():
      if param.grad is not None:
          print(f"{name} gradient:\n{param.grad}")
      else:
          print(f"{name} has no gradient")


Epoch: 0 Loss: 0.6997766494750977
0.weight gradient:
tensor([[0.0014, 0.0016],
        [0.0024, 0.0031]])
0.bias gradient:
tensor([0.0049, 0.0063])
2.weight gradient:
tensor([[0.0264, 0.0289]])
2.bias gradient:
tensor([0.0553])
Epoch: 100 Loss: 0.6929904818534851
0.weight gradient:
tensor([[-6.6484e-05,  1.8283e-04],
        [ 5.0340e-04, -2.4561e-04]])
0.bias gradient:
tensor([-0.0003,  0.0005])
2.weight gradient:
tensor([[ 2.4809e-05, -1.4614e-04]])
2.bias gradient:
tensor([0.0001])
Epoch: 200 Loss: 0.6451032757759094
0.weight gradient:
tensor([[-0.0008,  0.0018],
        [ 0.0140, -0.0146]])
0.bias gradient:
tensor([0.0007, 0.0039])
2.weight gradient:
tensor([[-0.0020, -0.0258]])
2.bias gradient:
tensor([0.0043])
Epoch: 300 Loss: 0.3552457094192505
0.weight gradient:
tensor([[-0.0256,  0.0136],
        [ 0.0125, -0.0151]])
0.bias gradient:
tensor([0.0051, 0.0011])
2.weight gradient:
tensor([[-0.0488, -0.0337]])
2.bias gradient:
tensor([0.0078])
Epoch: 400 Loss: 0.1696193665266037
0.